control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: false

    # 对你这套自定义框架，纯 SimulationRobot 数值仿真先保持 false
    simulation: false
    sim_real_time: true

    # 由 control_node 内部直接发布 joint_states
    publish_joint_state: true

    robot: hardwares::SimulationRobot
    parameters: "parameters.yaml"

    controllers:
      - controllers::ForwardController
      - controllers::CartesianMotionController
      # - controllers::JointMotionController
      - controllers::CartesianTrajectoryController

    default_controller: ""


SimulationRobot:
  ros__parameters:
    end_effector: ""

    joint_command_interface:
      - position
      - velocity
      - torque

    joint_state_interface:
      - position
      - velocity
      - torque

    init_joint_pose:
      - 0.0
      - 0.0
      - -3.0
      - 0.0
      - 0.0
      - 0.0
    command_interface:
      - mode
      - pose

    command_length:
      - 1
      - 6

    command_type:
      - int
      - double


ForwardController:
  ros__parameters:
    cmd_name: "position"

# JointMotionController:
#   ros__parameters:
#     cmd_name: "position"
#     speed: 0.2

# CartesianMotionController:
#   ros__parameters:
#     cmd_name: "pose"

CartesianTrajectoryController:
  ros__parameters:
    cmd_name: "pose"