control_node:
  ros__parameters:
    update_rate: 1000
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::DIANARobot
    controllers: 
      - controllers::JointMotionController
      - controllers::CartesianMotionController
      - controllers::CartesianTrajectoryController
      - controllers::ForwardController
      - controllers::RealtimeTestController
      - controllers::ForceDragController
      - controllers::RobotStateBroadcaster
      - controllers::PDMotionController
      - controllers::CartesianImpedancePDController
    default_controller: "controllers::CartesianImpedancePDController"

DIANARobot:
  ros__parameters:
    robot_ip: 192.168.10.75
    end_effector: ""
    # joint interface:
    joint_command_interface:
      - torque 
    joint_state_interface:
      - position
      - velocity
      - acceleration
      - torque
    # other interface:
    command_interface: [mode, pose]
    command_length: [2, 6]
    command_type: [int, double]
    state_interface: [T, c, g, external_torque, success, m]
    state_length: [16, 7, 7, 7, 1, 49]
    state_type: [double, double, double, double, double, double]

ForwardController:
  ros__parameters:
    cmd_name: "position"

JointMotionController:
  ros__parameters:
    cmd_name: "position"

CartesianImpedancePDController:
  ros__parameters:
    cmd_name: "torque"
     # Kx 和 Bx 必须是 6 个数：前 3 个是姿态 (旋转)，后 3 个是位置 (平移)
    Kx: [100.0, 100.0, 100.0,  200.0, 200.0, 200.0] # 姿态刚度设为 100，位置刚度设为 200
    Bx: [ 20.0,  20.0,  20.0,   40.0,  40.0,  40.0] # 阻尼设为刚度的平方根附近，抑制晃动
    
    # Kn 和 Bn 必须是 7 个数：对应 7 个关节的零空间（冗余自由度）控制
    Kn: [ 50.0,  50.0,  50.0,   50.0,  50.0,  50.0,  50.0] # 零空间刚度要比末端刚度软
    Bn: [ 10.0,  10.0,  10.0,   10.0,  10.0,  10.0,  10.0] # 基础阻尼，防止关节乱甩