control_node:
  ros__parameters:
    update_rate: 1000
    lock_memory: true
    simulation: false
    sim_real_time: false
    publish_joint_state: true
    robot: hardwares::DIANARobot
    controllers: 
      - controllers::JointMotionController
      - controllers::CartesianMotionController
      - controllers::CartesianTrajectoryController
      - controllers::CartesianTrajectoryDianaController
      - controllers::ForwardController
      - controllers::RealtimeTestController
      - controllers::ForceDragController
      - controllers::RobotStateBroadcaster
      # - controllers::PDMotionController
      - controllers::CartesianImpedancePDController
      - controllers::CartesianImpedancePDPlusController
      - controllers::CartesianTrajImpPDController
      - controllers::CartesianTrajImpPDPlusController
    default_controller: "controllers::CartesianImpedancePDController"

DIANARobot:
  ros__parameters:
    robot_ip: 192.168.10.75
    end_effector: ""
    # joint interface:
    joint_command_interface:
      - torque 
    joint_state_interface:
      - position
      - velocity
      - acceleration
      - torque
    # other interface:
    command_interface: [mode, pose]
    command_length: [2, 6]
    command_type: [int, double]
    state_interface: [T, c, g, external_torque, success, m, pose, position, velocity]
    state_length: [16, 7, 7, 7, 1, 49, 6, 7, 7]
    state_type: [double, double, double, double, double, double, double, double, double]

ForwardController:
  ros__parameters:
    cmd_name: "position"

JointMotionController:
  ros__parameters:
    cmd_name: "position"

CartesianImpedancePDController:
  ros__parameters:
    cmd_name: "torque"
    Kx: [2500.0, 2500.0, 2500.0,  500.0, 500.0, 500.0]  
    Bx: [ 150.0,  150.0, 150.0,   30.0,  30.0,  30.0]  
    Kn: [ 0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0]  
    Bn: [ 1.0,  1.0,  1.0,   1.0,  1.0, 1.0,  1.0]  

CartesianImpedancePDPlusController:
  ros__parameters:
    cmd_name: "torque"
    Kx: [10.0, 10.0, 10.0, 100.0, 100.0, 100.0]  
    Bx: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]  
    Kn: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]  
    Bn: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]  

CartesianTrajImpPDController:
  ros__parameters:
    cmd_name: "torque"
    # Kx: [2500.0, 2500.0, 2500.0,  500.0, 500.0, 500.0]  
    # Bx: [ 150.0,  150.0, 150.0,   30.0,  30.0,  30.0]  
    # Kn: [ 0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0]  
    # Bn: [ 1.0,  1.0,  1.0,   1.0,  1.0, 1.0,  1.0]  

    Kx: [300.0, 300.0, 300.0, 1000.0, 1000.0, 1000.0] 
    Bx: [7.0,  7.0,  7.0,  14.0,  14.0, 14.0] 
    Kn: [ 0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0] 
    Bn: [ 1.0,  1.0,  1.0,   1.0,  1.0, 1.0,  1.0] 

CartesianTrajImpPDPlusController:
  ros__parameters:
    cmd_name: "torque"
    Kx: [2500.0, 2500.0, 2500.0,  500.0, 500.0, 500.0]  
    Bx: [ 150.0,  150.0, 150.0,   30.0,  30.0,  30.0]  
    Kn: [ 0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0]  
    Bn: [ 1.0,  1.0,  1.0,   1.0,  1.0, 1.0,  1.0]  