control_node:
  ros__parameters:
    update_rate: 500
    lock_memory: true
    simulation: true
    sim_real_time: true
    publish_joint_state: true
    robot: hardwares::SimulationRobot
    parameters: "parameters.yaml"
    controllers: 
      - controllers::JointMotionController
      - controllers::CartesianMotionController
      - controllers::CartesianTrajectoryController
      - controllers::ForwardController
      - controllers::RealtimeTestController
      - controllers::ForceDragController
      - controllers::RobotStateBroadcaster
      - controllers::PDMotionController
      - controllers::CartesianImpedancePDController
    default_controller: ""

SimulationRobot:
  ros__parameters:
    end_effector: ""
    joint_command_interface:
      - position
      - velocity
      - torque
    joint_state_interface:
      - position
      - velocity
      - torque
    init_joint_pose:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] #[.0, -0.962, 1.730, -3.842, -1.843, 0.0]# 
    # [0.0, -0.5, 0.1, 2.0, 0.0, -1.5, .0] [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    command_interface: [mode, pose]
    command_length: [3, 6] # mode = 0: cartesian, 1: joint position 2: joint velocity 3: joint torque
    command_type: [int, double]

    state_interface: [T, c, g, external_torque, success, m]
    state_length: [16, 7, 7, 7, 1, 49]
    state_type: [double, double, double, double, double, double]
    # sensors: [ft_sensor]
    # ft_sensor: hardwares::FTDummySensor

# ft_sensor:
#   ros__parameters:
#     state_interface: [force]
#     state_length: [6]
#     sensor_ip: 192.168.110.101
#     sensor_port: 4008


ForwardController:
  ros__parameters:
    cmd_name: "position"

JointMotionController:
  ros__parameters:
    cmd_name: "position"

CartesianImpedancePDController:
  ros__parameters:
    cmd_name: "torque"
     # Kx 和 Bx 必须是 6 个数：前 3 个是姿态 (旋转)，后 3 个是位置 (平移)
    Kx: [100.0, 100.0, 100.0,  200.0, 200.0, 200.0] # 姿态刚度设为 100，位置刚度设为 200
    Bx: [ 20.0,  20.0,  20.0,   40.0,  40.0,  40.0] # 阻尼设为刚度的平方根附近，抑制晃动
    
    # Kn 和 Bn 必须是 7 个数：对应 7 个关节的零空间（冗余自由度）控制
    Kn: [ 50.0,  50.0,  50.0,   50.0,  50.0,  50.0,  50.0] # 零空间刚度要比末端刚度软
    Bn: [ 10.0,  10.0,  10.0,   10.0,  10.0,  10.0,  10.0] # 基础阻尼，防止关节乱甩
