control_node:
  ros__parameters:
    update_rate: 1000
    lock_memory: true
    simulation: false
    sim_real_time: true
    publish_joint_state: true
    robot: hardwares::SimulationRobot
    parameters: "parameters.yaml"
    controllers: 
      # - controllers::JointMotionController
      - controllers::CartesianMotionController
      - controllers::CartesianTrajectoryController
      # - controllers::CartesianTrajectoryDianaController
      # - controllers::ForwardController
      # - controllers::RealtimeTestController
      # - controllers::ForceDragController
      # - controllers::RobotStateBroadcaster
      # - controllers::CartesianImpedancePDController
      - controllers::CartesianTrajImpPDController
      # - controllers::JointMotionControllerDiana
      # - controllers::VariableImpedanceController
    default_controller: ""

SimulationRobot:
  ros__parameters:
    end_effector: ""
    joint_command_interface:
      - position
      - velocity
      - torque
    joint_state_interface:
      - position
      - velocity
      - torque
    init_joint_pose: 
    # [.0, -0.962, 1.730, -3.842, -1.843, 0.0]
     [0.2, -0.2, 0.25, -2.5, 0.0, 2.3, 0.4]
    #  [.0, -0.962, 1.730, -3.842, -1.843, 0.0] #[.0, -0.962, 1.730, -3.842, -1.843, 0.0]# 
    # [0.0, -0.5, 0.1, 2.0, 0.0, -1.5, .0] 
    command_interface: [mode, pose]
    command_length: [2, 6]
    command_type: [int, double]
    state_interface: [T, c, g, external_torque, success, m, pose, position, velocity, torque, pose_q_]
    state_length: [16, 7, 7, 7, 1, 49, 6, 7, 7, 7, 6]
    state_type: [double, double, double, double, double, double, double, double, double, double, double]
    # sensors:
    sensors: [ft_sensor]
    ft_sensor: hardwares::FTATISensor

ft_sensor:
  ros__parameters:
    sensor_ip: 192.168.124.10
    state_interface: [force]
    state_length: [6]   
    # sensors: [ft_sensor]
    # ft_sensor: hardwares::FTDummySensor

# ft_sensor:
#   ros__parameters:
#     state_interface: [force]
#     state_length: [6]
#     sensor_ip: 192.168.110.101
#     sensor_port: 4008


# ForwardController:
#   ros__parameters:
#     cmd_name: "position"

# JointMotionController:
#   ros__parameters:
#     cmd_name: "position"
#     speed: 0.2

# CartesianImpedancePDController:
#   ros__parameters:
#     cmd_name: "torque"
#      # Kx 和 Bx 必须是 6 个数：前 3 个是姿态 (旋转)，后 3 个是位置 (平移)
#     Kx: [10.0, 10.0, 10.0, 100.0, 100.0, 100.0] # 姿态刚度设为 100，位置刚度设为 200
#     Bx: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # 阻尼设为刚度的平方根附近，抑制晃动
    
#     # Kn 和 Bn 必须是 7 个数：对应 7 个关节的零空间（冗余自由度）控制
#     Kn: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # 零空间刚度要比末端刚度软
#     Bn: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0] # 基础阻尼，防止关节乱甩

# CartesianImpedancePDPlusController:
#   ros__parameters:
#     cmd_name: "torque"
#      # Kx 和 Bx 必须是 6 个数：前 3 个是姿态 (旋转)，后 3 个是位置 (平移)
#     Kx: [10.0, 10.0, 10.0, 100.0, 100.0, 100.0] # 姿态刚度设为 100，位置刚度设为 200
#     Bx: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # 阻尼设为刚度的平方根附近，抑制晃动
    
#     # Kn 和 Bn 必须是 7 个数：对应 7 个关节的零空间（冗余自由度）控制
#     Kn: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # 零空间刚度要比末端刚度软
#     Bn: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0] # 基础阻尼，防止关节乱甩

CartesianTrajImpPDController:
  ros__parameters:
    cmd_name: "torque"
     # Kx 和 Bx 必须是 6 个数：前 3 个是姿态 (旋转)，后 3 个是位置 (平移)
    Kx: [10.0, 10.0, 10.0, 100.0, 100.0, 100.0] # 姿态刚度设为 100，位置刚度设为 200
    Bx: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # 阻尼设为刚度的平方根附近，抑制晃动
    
    # Kn 和 Bn 必须是 7 个数：对应 7 个关节的零空间（冗余自由度）控制
    Kn: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # 零空间刚度要比末端刚度软
    Bn: [6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0] # 基础阻尼，防止关节乱甩

# VariableImpedanceController:
#   ros__parameters:
#     cmd_name: "torque"
    
#     # 基础阻抗参数 (XY方向及旋转方向保持固定)
#     Kx: [500.0, 500.0, 500.0, 2500.0, 2500.0, 2500.0] 
#     Bx: [7.0, 7.0,  7.0,  80.0,  80.0, 80.0] 
#     Kn: [ 0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0] 
#     Bn: [ 1.0,  1.0,  1.0,   1.0,  1.0, 1.0,  1.0] 

#     # --- 1. 二次规划 (QP) 优化权重 ---
#     # Q_weight: 力跟踪精度权重，越大越追求力的准确
#     # R_weight: 刚度平滑权重，越大刚度变化越慢、越保守
#     Q_weight: 10.0           
#     R_weight: 0.01           
    
#     # --- 2. 力控参数 (Z方向) ---
#     F_des_z: 5.0            # 期望接触力 (N)，根据实际需求设置正负
#     F_max_z: 10.0            # 最大安全力限制 (N)
#     Kp_f: 0.0                # 力外环 P (建议先设为0，只用优化器调整)
#     Ki_f: 0.0                # 力外环 I (建议先设为0)
    
#     # --- 3. 刚度边界 (Z方向) ---
#     Kz_min: 500.0             # 最小刚度 (自由空间/软接触)
#     Kz_max: 2500.0           # 最大刚度 (硬接触)
